[package]
name = "myrockdb-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
rocksdb = "0.19.0"
json = "0.12.4"
bytes = "1.3.0"
